##################################################
### Configfile for Snakefile-scRNA-seq in YAML ###
##################################################

### Reference Genomes ### 
reference_unzip: /pellmanlab/stam_niko/refgenomes/Gencode/v25/GRCh38.primary_assembly.genome.fa
ref_unzip_wdict: /pellmanlab/stam_niko/refgenomes/Gencode/v25/wdict/GRCh38.primary_assembly.genome.fa
reference_gtf_unzip: /pellmanlab/stam_niko/refgenomes/Gencode/v25/gencode.v25.primary_assembly.annotation.gtf
readlength: 100

### Reference RPE-1 Data ###
normal: /singlecellcenter/RPE-1/bamlinks/GRCh38/RPE_bulk.bam
normal_name: RPE-Bulk2 #RPE1-bulk
alleles: /czlab/Data/RPE-1_Genotyping_GRCh38/v.1/RPE-1.hets.vcf.gz

### Samples Files ###
samples: SIS1025f_samples.txt

### Picard Options ###
# for configuring picard "max_records_in_ram", determines memory usage 
# TODO: make this argument optional in the snakefile
max_records: 500000 # default

### Temporary File Directory ###
# location for temporary files generated by gatk and other tools (will overflow /tmp/)
# TODO: make this the default in the snakefile 
# NOTE: For cluster usage, instead make a folder in high-performance /cluster/ storage
tmp_dir: 'tmp'

### Thread, CPU, and Core Settings ###
MAX_THREADS: 16
DEFAULT_THREADS: 4

### GATK Options ### 
GATK: 'gatk --java-options "-Xmx16G -XX:+UseParallelGC -XX:ParallelGCThreads=8"'
PICARD_OPTIONS: f'--TMP_DIR 'tmp' --MAX_RECORDS_IN_RAM 16 --USE_JDK_DEFLATER --USE_JDK_INFLATER --COMPRESSION_LEVEL 5'
GATK_FILTERS: ("-RF MappingQualityReadFilter --minimum-mapping-quality 30 -RF OverclippedReadFilter --filter-too-short 50")
